package:
  format-version: "1.0.0"
  name: "gfx_apps_sam_l22"
  version: "3.10.0"
  type: "application"
  status: "production"

  dependencies:
    - name: "gfx"
      type: "package"
      version: "3.11.1"
