format_version: v1.0
type: UniqueComponent
attributes: {id: le_gfx_slcd}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: EnableBiasBuffer}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '650', y: '60', id: le_gfx_slcd}
