configName: slcd1_xpro_l22
folderName: legato_qs_l22_slcd1_xpro
format_version: v1.0
frameworkPath: ..\..\..
processor: ATSAML22N18A
projectName: legato_quickstart_slcd1
settings:
  PackageFilter: aerospace;audio;azure-rtos-threadx;azure_rtos;bsp;core;crypto;csp;Devices;dev_packs;gfx;gfx_apps_pic32mz_da;gfx_apps_sam_d5x_e5x;gfx_apps_sam_e70_s70_v70_v71;gfx_apps_sam_l22;harmony-services;net;quick_docs;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAML22_DFP\3.7.83\atdf\ATSAML22N18A.atdf
